#!/bin/bash
#https://pawelgrzybek.com/change-macos-user-preferences-via-command-line/
#http://brettterpstra.com/2018/09/26/shell-tricks-toggling-dark-mode-from-terminal/
osascript -e 'tell app "System Events" to tell appearance preferences to set dark mode to true'