#!/bin/bash

alias go-sa='ssh $NEW_SSH_USER@aem-staging-author1.vnerd.com'
alias go-sp1='ssh $NEW_SSH_USER@aem-staging-publish1.vnerd.com'
alias go-sd1='ssh $NEW_SSH_USER@aem-staging-dispatcher1.vnerd.com'
alias go-pa='ssh $NEW_SSH_USER@aem-production-author1.vnerd.com'
alias go-pp1='ssh $NEW_SSH_USER@aem-production-publish1.vnerd.com'
alias go-pp2='ssh $NEW_SSH_USER@aem-production-publish2.vnerd.com'
alias go-pp3='ssh $NEW_SSH_USER@aem-production-publish3.vnerd.com'
alias go-pd1='ssh $NEW_SSH_USER@aem-production-dispatcher1.vnerd.com'
alias go-pd2='ssh $NEW_SSH_USER@aem-production-dispatcher2.vnerd.com'
alias go-pd3='ssh $NEW_SSH_USER@aem-production-dispatcher3.vnerd.com'